export const petDetails=[
  {
    id: 1,
    img: "https://static.vecteezy.com/system/resources/thumbnails/005/857/332/small/funny-portrait-of-cute-corgi-dog-outdoors-free-photo.jpg",
    name: "Jackey",
    brid: "Cavalier King Charles",
    type: "Dog",
    age: "6 Months",
    Gender: "Male",
    Weight: "6-7 Kg",
    Height: "10-14 Inch",
    Colour: "White",
  },
  {
    id: 2,
    img: "https://media.istockphoto.com/id/513385146/photo/cute-white-little-rabbit-peeking-out-of-hole.jpg?s=612x612&w=0&k=20&c=aP7CIcMUK058WAzmce5YxhZsjYwD2Op6G2oBn12Qd9o=",
    name: "poops",
    brid: "angora rabbit",
    type: "rabbit",
    age: "2 Year",
    Gender: "Male",
    Weight: "4-5 Kg",
    Height: "18-20 Inch",
    Colour: "White",
  },
  {
    id: 3,
    img: "https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",
    name: "boby",
    brid: "angora rabbit",
    type: "rabbit",
    age: "2 Year",
    Gender: "Male",
    Weight: "4-5 Kg",
    Height: "18-20 Inch",
    Colour: "White",
  },
];
